### PR TITLE
WIP: Use a sequence instead of raw string 

### PR DESCRIPTION
**Pull request by fridex**
Fixes: #6

### CODE REVIEW

**Comment by fridex** [comment]
We will need to wait for https://github.com/kennethreitz/delegator.py/pull/52 before merging this. delegator library we use has issues with this change.

**Comment by goern** [comment]
@fridex is this still relevant?

**Comment by goern** [comment]
@fridex is this still relevant?

**Comment by fridex** [comment]
This is really old code. We use run_command that should handle escaping in one place - in thoth-common.

**Pull request closed without merging**
