### PR TITLE
migrate OpenShift templates to thoth-application

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
@harshad16 @goern should we move all of them to thoth-application?

**Comment by goern** [comment]
ja, it seems to be an isolated component, and the BC should land in test overlay, the rest goes to base I guess...

**Comment by harshad16** [comment]
> @harshad16 @goern should we move all of them to thoth-application?

yes, we should, I will create an application for package-extract in thoth-application.

**Comment by fridex** [comment]
> I will create an application for package-extract in thoth-application.

I'll open a PR with argo workflow replacing the job approach.

**Pull request merged**
