### PR TITLE
fixing coala errors/warnings

### PR DESCRIPTION
**Pull request by goern**
fixing formating problems introduced by https://github.com/thoth-station/package-extract/pull/31

### CODE REVIEW

**Comment by goern** [comment]
@fridex could you have a look at https://zuul.thoth-station.ninja/logs/51/51/a19b8ed31ba6a322c2141b2a403433ad33aa4bb0/check/linters/9a446fc/job-output.txt.gz#_2018-06-21_14_05_00_229462

**Comment by goern** [comment]
nooo, does not lg :) coala is complaining about the readme... can we tell LineCountBear to accept large files?

**Comment by fridex** [comment]
> nooo, does not lg :) coala is complaining about the readme... can we tell LineCountBear to accept large files?

#52

**Pull request merged**
