### PR TITLE
Propagate requirements info as used by AICoE-CI

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/prescriptions/pull/18523

## Description

See related discussion in https://github.com/thoth-station/prescriptions/pull/18523. The goal here is to propagate information about requirements that were used during the image build. It is expected to place Pipfile/Pipfile.lock to `/opt/aicoe-ci` directory by AICoE-CI to make this work properly.

### CODE REVIEW

**Comment by fridex** [comment]
CC @harshad16 @pacospace

**Comment by fridex** [comment]
@harshad16 would it be possible to place Pipfile+Pipfile.lock (and eventually.thoth.yaml) to `/opt/aicoe-ci` in AICoE-CI?

**Comment by harshad16** [comment]
yes @fridex  it will be
i will take up on this task next week
if that is okay ?

**Comment by fridex** [comment]
> yes @fridex it will be i will take up on this task next week if that is okay ?

Thanks, that would be great. No rush, not super critical 👍🏻

**Review by pacospace — APPROVED** [review]
:100 Thanks!!

**Comment by fridex** [comment]
/hold

Until available in AICoE-CI

**Comment by fridex** [comment]
/unhold

Available in AICoE-CI.

**Pull request merged**
