### PR TITLE
Automatic update of dependency requests from 2.18.4 to 2.19.1

### PR DESCRIPTION
**Pull request by harshad16**
Dependency requests was used in version 2.18.4, but the current latest version is 2.19.1.

### CODE REVIEW

**Comment by fridex** [comment]
:tada:

**Comment by goern** [comment]
Shouldnt we pin down the versions used in the Pipfile itself so that we only allow the transitive dependencies to be volatile? If we exclude certain versions of packages (due to recommendations by Thoth) we need to start pinning version in Pipfile anyway.

Shall we describe how we image dependencies to be managed in a doc? @fridex

**Comment by fridex** [comment]
> Hmm it's not only updating 'requests' but also all the other dependencies, this is
> a) misleading

We are requiring requests in our [Pipfile](https://github.com/thoth-station/package-extract/blob/master/Pipfile#L10). By updating requests there are also updated all the transitive dependencies introduced by requests - so basically we are updating requests dependency subgraph. 

> b) intruding merge conflicts with other update PRs and

As we are opening PRs for each direct dependency update, I think PRs will occur - we are working on one file in multiple PRs. Does sesheta mark PRs with merge conflicts with some label? We could automate rebasing/updates for conflicting PRs. Now if you close the conflicting PR and delete branch, the PR is automatically updated on top of the current master (name of branches are relevant when pushing changes).

> Shouldnt we pin down the versions used in the Pipfile itself so that we only allow the transitive dependencies to be volatile? If we exclude certain versions of packages (due to recommendations by Thoth) we need to start pinning version in Pipfile anyway.

I don't think its a good approach. In Pipfile we state dependencies of our application - we should restrict versions there only if something is braking due to dependency version (see recent yarl issues). All the version locking should be done during dependency resolution.

In case of thoth, this version locking will be done during version resolution as well for the software stack. The main reasoning is that we can (and will) end up with different versions for different runtime environment - we still need keeping what is the original software stack specification. Thoth will be basically a function that is giving guidance during pinning versions for direct and all the transitive dependencies.

> Shall we describe how we image dependencies to be managed in a doc? @fridex

+1

**Comment by fridex** [comment]
Let's close this to test kebechet deployment.

**Pull request closed without merging**
